num1 = int(input("Enter number 1 here:- "))
num2 = int(input("Enter number 2 here:- "))
print("addtion :-",num1+num2)
print("difference :-",num1-num2)
print("product :-",num1*num2)
print("quotient :-",num1/num2)